game.sprites = {
  bigBlue: game.graphics.Sprite({
    image: game.assets.bigblue,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  flag: game.graphics.Sprite({
    image: game.assets.flag,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  floor: game.graphics.Sprite({
    image: game.assets.floor,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  hedge: game.graphics.Sprite({
    image: game.assets.hedge,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 250,
  }),
  grass: game.graphics.Sprite({
    image: game.assets.grass,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  lava: game.graphics.Sprite({
    image: game.assets.lava,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  rock: game.graphics.Sprite({
    image: game.assets.rock,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wall: game.graphics.Sprite({
    image: game.assets.wall,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  water: game.graphics.Sprite({
    image: game.assets.water,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordBigBlue: game.graphics.Sprite({
    image: game.assets.wordBigBlue,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordFlag: game.graphics.Sprite({
    image: game.assets.wordFlag,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordIs: game.graphics.Sprite({
    image: game.assets.wordIs,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordKill: game.graphics.Sprite({
    image: game.assets.wordKill,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordLava: game.graphics.Sprite({
    image: game.assets.wordLava,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordPush: game.graphics.Sprite({
    image: game.assets.wordPush,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordRock: game.graphics.Sprite({
    image: game.assets.wordRock,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordSink: game.graphics.Sprite({
    image: game.assets.wordSink,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordStop: game.graphics.Sprite({
    image: game.assets.wordStop,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordWall: game.graphics.Sprite({
    image: game.assets.wordWall,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordWater: game.graphics.Sprite({
    image: game.assets.wordWater,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordWin: game.graphics.Sprite({
    image: game.assets.wordWin,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
  wordYou: game.graphics.Sprite({
    image: game.assets.wordYou,
    spriteHeight: 24,
    spriteWidth: 24,
    numFrames: 3,
    timePerFrame: 100,
  }),
};
